#pragma once

// Name: RegainEart-FirtstStrike, Version: Version-1


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__KillSelf_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__KillSelf_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__ReviveSelf_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__ReviveSelf_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__KillAllEnemies_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__KillAllEnemies_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__TraceAllEnemies_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__TraceAllEnemies_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__SetCurrentRoundToLastRound_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__SetCurrentRoundToLastRound_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__TeleportToBeginOfLastRound_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__TeleportToBeginOfLastRound_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__TriggerGameWin_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__TriggerGameWin_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__TriggerGameLoose_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__TriggerGameLoose_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__CloseMenu_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__CloseMenu_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__HealSelf_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__HealSelf_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__SetCurrentRoundToRound2_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__SetCurrentRoundToRound2_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__SpawnBoss_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__SpawnBoss_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__SwitchToSpectatorCam_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__SwitchToSpectatorCam_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__GrantExtremeHealth_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__GrantExtremeHealth_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__DropRandomWeapon_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__DropRandomWeapon_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__DropRandomGrenade_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__DropRandomGrenade_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__W_PawnAdminAndCheatMenu_SetCurrentRoundToRound5_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__W_PawnAdminAndCheatMenu_SetCurrentRoundToRound5_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__W_PawnAdminAndCheatMenu_SetCurrentRoundToRoundx_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__W_PawnAdminAndCheatMenu_SetCurrentRoundToRoundx_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__W_PawnAdminAndCheatMenu_ResetLeaderboardEntryOfRunningMatch_1_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__W_PawnAdminAndCheatMenu_ResetLeaderboardEntryOfRunningMatch_1_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__W_PawnAdminAndCheatMenu_ResetSteamStatsAndAchivements_1_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__W_PawnAdminAndCheatMenu_ResetSteamStatsAndAchivements_1_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__W_PawnAdminAndCheatMenu_ResetSteamStats_1_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__W_PawnAdminAndCheatMenu_ResetSteamStats_1_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__W_PawnAdminAndCheatMenu_SetCurrentRoundToRoundx_1_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__W_PawnAdminAndCheatMenu_SetCurrentRoundToRoundx_1_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.BndEvt__W_PawnAdminAndCheatMenu_btSetLastRoundAndTeleport_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_BndEvt__W_PawnAdminAndCheatMenu_btSetLastRoundAndTeleport_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.ExecuteUbergraph_W_PawnAdminAndCheatMenu
struct UW_PawnAdminAndCheatMenu_C_ExecuteUbergraph_W_PawnAdminAndCheatMenu_Params
{
	int                                                EntryPoint;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function W_PawnAdminAndCheatMenu.W_PawnAdminAndCheatMenu_C.CloseAdminCheatMenu__DelegateSignature
struct UW_PawnAdminAndCheatMenu_C_CloseAdminCheatMenu__DelegateSignature_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
